### ISSUE TITLE
Change SFUEL documentation structure

### ISSUE THREAD

**Issue by ebruoguzberk** [skalenetwork/docs.skale.network#35]
For the SFUEL documentation. SE team needs an answer to this question. How can I handle SFUEL? Where can I retrieve it? 

Our suggestion is this structure:

* Description of SFUEL
* Options to handle SFUEL
     - Send directly to your user as airdrop
     - Set up Faucet
     - POW
     - Use new npm package (POW + Faucet) 
* SFUEL Architecture etherbase, contract info, SFUEL distribution what is that mean Etherbase will have 10x more than Schain owner, how will it benefit me as a SKALE Chain owner.

**Comment by TheGreatAxios** [comment]
Resolved by #106
