### ISSUE TITLE
Add role descriptions to permissions.adoc

### ISSUE THREAD

**Issue by ebruoguzberk** [skalenetwork/docs.skale.network#39]
**Is your feature request related to a problem? Please describe.**
A separate page describes the ROLES and why they needed to be given. the page permissions.adoc is a better-simplified version, but it's hard to guess the description for each ROLE. 

**Describe the solution you'd like**
Please add descriptions for each ROLE. 

**Describe alternatives you've considered**
Example:  
CONSTANT_SETTER_ROLE
Messages are limited to 1M gas by default. To change this limit, use this role to set it to another value.

**Comment by TheGreatAxios** [comment]
Pull data from admin-ui for list of roles and replace List of Permissions Page

**Comment by TheGreatAxios** [comment]
Move List of Permissions -> Permissions Functionality or Using Permissions
